### ISSUE TITLE
Search Button height Issue

### ISSUE THREAD

**Issue by gaurangkeluskar22** [Keegan-20/YumBite-Foods#1]
## The search Button's height looks small as compared to the height of the search input box
![image](https://github.com/Keegan-20/YumBites-Food/assets/43683829/2d3a87cc-fb78-496b-80b8-fd207a04fdc5)

**Comment by gaurangkeluskar22** [comment]
Hi, @Keegan-20 Can you please assign this issue to me?

**Comment by Keegan-20** [comment]
search button is deliberately kept of smaller size inorder to compliance with UI structure.Im marking it as closed.

**Comment by gaurangkeluskar22** [comment]
Hi @Keegan-20 understood, but the UI does not look good.

**Before**
![image](https://github.com/Keegan-20/YumBites-Food/assets/43683829/8780716c-9235-4304-b5a4-d30b88022c5e)

**After removing "my-2" class**
![image](https://github.com/Keegan-20/YumBites-Food/assets/43683829/4589cc9a-987b-4ebd-a727-868f0e315449)

![image](https://github.com/Keegan-20/YumBites-Food/assets/43683829/cc218a28-7ee8-41c8-9b8b-3341fc497099)
